export const translationsFi: Record<string, string> = {
  "The undertaking applies circular economy principles by delivering its services digitally and minimising the use of materials. IT equipment is acquired for long-term use and replaced only when technically necessary. The undertaking does not engage in physical production or material-intensive processes.": 
  "Yritys soveltaa kiertotalousperiaatteita tarjoamalla palvelut digitaalisesti ja minimoimalla materiaalien käytön. IT-laitteet hankitaan pitkäaikaiseen käyttöön ja niitä vaihdetaan vain teknisen tarpeen perusteella. Yrityksessä ei ole fyysistä tuotantoa eikä materiaalivaltaisia prosesseja.",

  "The reporting period covers 6 October 2025 to 31 December 2025. The undertaking commenced its operations during this period. No turnover was generated during the reporting period. Consequently, greenhouse gas emission intensity per turnover is not considered a meaningful performance indicator for this reporting period. Financial figures are based on the accounting information available at the reporting date. The final year-end financial statements had not yet been prepared at the time of reporting.":
  "Raportointikausi kattaa ajanjakson 6.10.2025–31.12.2025. Yritys käynnisti toimintansa tämän jakson aikana. Raportointikaudella ei kertynyt liikevaihtoa, joten kasvihuonekaasupäästöjen intensiteettiä suhteessa liikevaihtoon ei pidetä tarkoituksenmukaisena tunnuslukuna. Taloudelliset tiedot perustuvat raportointihetkellä käytettävissä olleisiin kirjanpitotietoihin. Tilinpäätöstä ei ollut vielä laadittu raportin valmistuessa.",

  "During the reporting period, total electricity consumption amounted to 0.04951 MWh (49.51 kWh). Scope 2 greenhouse gas emissions (location-based) were calculated using the average emission factor for electricity generation in Finland (26 gCO₂/kWh). Based on this methodology, Scope 2 emissions amount to 0.001287 tCO₂e. Values in the report are presented with two decimal precision; therefore, Scope 2 emissions are displayed as 0.00 tCO₂e, although the unrounded value is included in the total emissions calculation.":
  "Raportointikauden aikana sähkön kokonaiskulutus oli 0,04951 MWh (49,51 kWh). Scope 2 -kasvihuonekaasupäästöt (sijaintiperusteiset) laskettiin käyttämällä Suomen sähköntuotannon keskimääräistä päästökerrointa (26 gCO2/kWh). Tämän menetelmän perusteella Scope 2 -päästöt ovat 0,001287 tCO2e. Raportin arvot esitetään kahden desimaalin tarkkuudella, minkä vuoksi Scope 2 -päästöt näytetään muodossa 0,00 tCO2e, vaikka pyöristämätön arvo on mukana kokonaispäästölaskennassa. Yrityskohtaisia Scope 3 -tietoja esitetään valituista olennaisiksi arvioiduista kategorioista, joista oli saatavilla riittävän luotettavaa tietoa raportointikauden aikana. Tämän perusteella yritys tunnisti luokan 2 Capital Goods merkittävimmäksi raportoiduksi Scope 3 -kategoriaksi. Tähän luokkaan sisältyvät Samsung Galaxy Book5 Pro 14 -kannettava tietokone ja Logitech MX Master 4 -hiiri, jotka hankittiin yrityksen käyttöön raportointikauden aikana.",

  "The undertaking had no employees during the reporting period and therefore no additional social disclosures are applicable.":
  "Yrityksellä ei ollut työntekijöitä raportointikaudella, joten muita sosiaalisia tietoja ei sovelleta.",

  "The undertaking is a sole proprietorship and does not have a separate governance body. Governance responsibilities rest with the entrepreneur.":
  "Yritys on yksityinen elinkeinoharjoittaja, eikä sillä ole erillistä hallintoelintä. Hallintovastuu on yrittäjällä."
};